apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realworld-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - realworld.example.com
      secretName: realworld-tls
  rules:
    - host: realworld.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: realworld-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realworld-frontend
                port:
                  number: 80
